### ISSUE TITLE
I want that people having admin role can assign tasks for the employees

### ISSUE THREAD

**Issue by lalitofficial** [aiforkidsofficial/app#1]
WE have the front end called tasks, but we want to make it work like admin role can assign tasks for the employees, and super admin can assign any role to all.

Mainly the roles will be 
Super Admin,
Admin - Can control everything in their team like ( Video Management Department, or Photo Editing Department , each department will have own admin )
Member ( Members or employees divided into teams )

**Comment by AtmegaBuzz** [comment]
done
